### ISSUE TITLE
4WD config file for FLuidNC

### ISSUE THREAD

**Issue by kaosbeat** [jamescarruthers/PlotterXY#10]
Documentetation in how to configure the 4WD option is scarce

taking this file https://github.com/jamescarruthers/PlotteRXY/blob/main/Firmware/FYSETCE4_plotterxy.yaml as a starting option, I think I need to add a` motor1:` section with the same layout as `motor0:` to both  x and y axes.

I'm using this table from https://github.com/FYSETC/FYSETC-E4

and I believe copying the motor0: section and changing 

```
axes:
 x: 
    motor1:
      step_pin: gpio.33
      direction_pin: gpio.32:high
 y: 
    motor1:
      step_pin: gpio.16
      direction_pin: gpio.17:high

```

should already be a step in the good direction.
Anything important I need to change/add not listed here?

**Comment by kaosbeat** [comment]
That was not enough.
I had to change the address of the stepper controllers as well.  So the sections
```

      tmc_2209:
        uart_num: 2
        addr: X
```

change X according to the table 

```
# Board stepper driver address and gpio
# axis  add   step  dir
# x     1     27    26
# y     3     33    32
# z     0     14    12
# e     2     16    17
```


```
axes: 
  x: 
    motor1:
      tmc_2209:
        addr: 3
        step_pin: gpio.33
        direction_pin: gpio.32:high
  y: 
    motor1:
      tmc_2209:
        addr: 2
        step_pin: gpio.16
        direction_pin: gpio.17:high
```
